### PR TITLE
Fix for Gruntfile.js path

### PR DESCRIPTION
**Pull request by RoverWire**
There was an space that brokes the search path, and append .js extensión on the options.

this solves #73

### CODE REVIEW

**Comment by ealves-pt** [comment]
@RoverWire I don't think we need to append the `.js`extension to filenames. Those names are used inside a `require` [here](https://github.com/kokarn/atom-grunt-runner/blob/master/lib/parse-config-task.coffee#L19) and that method is called here [here](https://github.com/kokarn/atom-grunt-runner/blob/master/lib/grunt-runner-view.coffee#L97).

And as far as I know, we don't need to specify the extension when requiring a file. Also, omitting the extension allows us to retrieve files with `.coffee` extension.

Can you test your changes without the extension? Also, try it with a gruntfile written in CoffeeScript to make it also works.

**Comment by RoverWire** [comment]
Ok, let me try... cause in Ubuntu seems to need .js extension since the package doesn't found the file:
atom

So, I think that .js is not appended on any time.

**Comment by RoverWire** [comment]
@ealves-pt Done!  You was right, it works fine without extensions.

**Comment by kokarn** [comment]
Thank you for your contribution! Will publish patch today :+1:

**Pull request merged**
