### PR TITLE
Fixed multiple views being displayed

### PR DESCRIPTION
**Pull request by ealves-pt**
Possible fix for #84.

When the plugin is enabled and disabled multiple times in the same session
it no longer displays multiple windows.

Also changed indentation size from 4 spaces to 2 spaces.

### CODE REVIEW

**Comment by kokarn** [comment]
Why did you change indentation? 
This will mess up the git balme and history :/ 
Is there some other reason than personal preference?

**Comment by ealves-pt** [comment]
Predefined from my IDE. But you are right, I will revert it to avoid this.

**Comment by kokarn** [comment]
Is it really? I'm running atom but have 4. 
Might be a setting I set when I started using it tho, don't remember ^^
I'll publish a new version with the fixes

**Comment by ealves-pt** [comment]
You have released the code with the entire PR reverted. Sorry. There is a PR with the indentation reverted and the bug fixed.

**Comment by kokarn** [comment]
Damn, this is a mess ^^
Updated on apm with a new patch now :)

**Comment by ealves-pt** [comment]
Thanks mate. Next time we will nail it :+1:

**Comment by kokarn** [comment]
Yeah, no problem! We got this ;)

**Pull request merged**
