### PR TITLE
Add support to list all tasks in a multi task.

### PR DESCRIPTION
**Pull request by DSpeckhals**
Currently for multi tasks, all sub tasks are run. This request gives the option to select a subtask in addition to the whole multi task. See #1. This is my first shot at Coffeescript, so feel free to correct where necessary.

An example task that has the ability to define multiple sub tasks is [grunt-contrib-requirejs](https://github.com/gruntjs/grunt-contrib-requirejs). An example Gruntfile could could be:

```javascript
module.exports = function(grunt) {
    "use strict";

    // Build configuration
    grunt.initConfig({
        pkg: grunt.file.readJSON("package.json"),
        requirejs: {
            compile: {
                options: {
                    baseUrl: "js",
                    name: "main",
                    mainConfigFile: "js/app/js/main.js",
                    optimizeAllPluginResources: true,
                    paths: {
                        main: "app/js/main"
                    },
                    out: "js/dist/base.min.js"
                }
            },
            compileRetail: {
                options: {
                    baseUrl: "js",
                    name: "main",
                    mainConfigFile: "js/app/js/main-retail.js",
                    optimizeAllPluginResources: true,
                    paths: {
                        main: "app/js/main-retail"
                    },
                    out: "js/dist/retail.min.js"
                }
            }
        },
        jshint: {
            options: {
                jshintrc: true
            },
            all: ["js/app/js/**/*.js"]
        },
        jsdoc: {
            dist: {
                src: ["js/app/js/**/*.js", "README.md"],
                dest: "js/docs"
            }
        }
    });

    // Run the requirejs optimizer/build
    grunt.loadNpmTasks("grunt-contrib-requirejs");

    // Run jshint
    grunt.loadNpmTasks("grunt-contrib-jshint");

    // Build the documentation
    grunt.loadNpmTasks("grunt-jsdoc");

    // Register the default build task
    grunt.registerTask("default", ["jshint", "requirejs", "jsdoc"]);
};
```

### CODE REVIEW

**Comment by kokarn** [comment]
Can you test this against the latest master? Just to make sure it's still working.

**Comment by DSpeckhals** [comment]
I can do that within the next few days...I'll just have to dust it off a bit.

**Comment by kokarn** [comment]
Yeah no problem, anytime's fine

**Comment by DSpeckhals** [comment]
I rebased to your master, and it still works as expected. These are the parsed tasks that were returned in the above example:

- default
- requirejs
- requirejs:compile
- requirejs:compileRetail
- jshint
- jsdoc

I'm happy with the results.

**Comment by ealves-pt** [comment]
@DSpeckhals, @kokarn

I will merge this into the master and use it during the day. If everything is OK we can then release it. I will leave an update here by tomorrow morning.

Thanks for the PR :+1:

**Comment by kokarn** [comment]
Sounds good to me. Just ping me when you are satisfied it's working as intended

**Comment by ealves-pt** [comment]
Good for publish :+1:

**Comment by kokarn** [comment]
Live and published in 0.14.0 :+1: Thanks! <3

**Pull request merged**
